github.com:
    users:
        Dimesyboy:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Dimesyboy
